on: [push]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .
      - uses: javidalpe/cognition-deploy-action@v1.2.0
        id: deploy
        with:
          personal-access-token: ${{secrets.COGNITION_RUN}}
      - run: echo "The public link to the task is ${{ steps.deploy.outputs.link }}"
